### ISSUE TITLE
Dynamic loading of header/footer only works in firefox, not chrome

### ISSUE THREAD

**Issue by kcolletripp** [UPOD-2016/UPOD#5]
Can somebody please check the script, as evident in test.html, and fix compatibility with chrome

**Comment by kcolletripp** [comment]
you loaded 2 external css sheets, 1 external jquery sheet, added a viewport and it doesn't work on chrome anyway.
![chrome](https://cloud.githubusercontent.com/assets/10841867/15639501/8b582bb6-25fa-11e6-9e15-fec2e81f5056.png)

**Comment by kcolletripp** [comment]
![chrome_errors](https://cloud.githubusercontent.com/assets/10841867/15639663/9b55f974-25fc-11e6-9e41-4cf424ea1a39.png)

**Comment by VikSharma12** [comment]
![screen shot 2016-05-30 at 12 22 14 am](https://cloud.githubusercontent.com/assets/19335462/15639666/a3b8413a-25fc-11e6-9d57-61425c387a02.png)

**Comment by ryanmak** [comment]
http://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local

looks like chrome won't allow local host viewing on javascript enabled web pages. If we host this on a live server, it should work as normal (says the people on stackOverflow).

**Comment by swar8080** [comment]
You can get around this while developing locally by disabling chromes security features which are blocking the request. Just be sure you don't visit any other websites within this instance of chrome.

Run this command or create a shortcut:
`"C:\path\to\chrome.exe" --user-data-dir="C:/Chrome dev session" --disable-web-security`
http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by kcolletripp** [comment]
`google-chrome --disable-web-security --user-data-dir` works on linux based distros. Thank you for the heads up.
