### ISSUE TITLE
Login Page needs to be fixed

### ISSUE THREAD

**Issue by kcolletripp** [UPOD-2016/UPOD#7]
login-page.html currently appears to have missing css somewhere. It should be a box, centered, with a username and password field and a button to login.

It currently looks like this:
![janky](https://cloud.githubusercontent.com/assets/10841867/15717556/83e20850-27f5-11e6-816d-812d9491db21.png)

**Comment by epicdelia** [comment]
fixed 
![image](https://cloud.githubusercontent.com/assets/10716863/15722945/29d152bc-280e-11e6-802f-95e93c831e3e.png)

**Comment by kcolletripp** [comment]
Can confirm for fix. Closing.
