### ISSUE TITLE
Push menu button relocation

### ISSUE THREAD

**Issue by kcolletripp** [UPOD-2016/UPOD#8]
Push menu button needs to be in the header

As can be seen in the picture, it is below.

![not_pushed](https://cloud.githubusercontent.com/assets/10841867/15717728/49c997f4-27f6-11e6-98bb-0a10d3f14912.png)

**Comment by rmoro** [comment]
Is this still relevant? Please close if not!

**Comment by mikeroher** [comment]
Closing due to removal of the menu button.
