### ISSUE TITLE
Push menu not taking up top-left corner

### ISSUE THREAD

**Issue by kcolletripp** [UPOD-2016/UPOD#9]
Currently it pushes the header to the right, but doesn't take up the space.

![pushed](https://cloud.githubusercontent.com/assets/10841867/15717812/a7476ea6-27f6-11e6-85eb-d8dceafaf6a4.png)

**Comment by rmoro** [comment]
.icon_menu {
  position: absolute;
  top: 0;
  left: 0;
}

might do it

**Comment by rmoro** [comment]
Closing since this is no longer relevant.
